### ISSUE TITLE
Pressing Back on Browser recovers deleted Page

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#258]
This is more a question. When you go back on the browser, after you deleted a page, the page shows up in the bar. It shouldn't show up, right?

**Comment by mila-sevilla** [comment]
I checked how Notion handles going back to a deleted page and I think it makes sense for us to also show a banner with possible actions, e.g. restore and delete page. What do you think @pzhine @jrceno ?

<img width="1437" alt="Screenshot 2020-08-18 at 12 12 32" src="https://user-images.githubusercontent.com/41082332/90501191-3dded800-e14c-11ea-8677-74fec2b87d5e.png">

**Comment by pzhine** [comment]
I like that idea @mila-sevilla , but let's wait on that until we have an archive tab. I'll close this for now, and reference it in #413.
