### ISSUE TITLE
Pages => Search box loses focus

### ISSUE THREAD

**Issue by pzhine** [databyss-org/databyss#277]
**Observed behavior**
1. Go to Pages in the navbar and click a page
2. Click into the search box
3. The Navbar switches to search and the search box loses focus

**Expected behavior**
Typing a search query in the Pages sidebar should not change the navbar to search. Instead, it should filter the pages with the search query.

**Comment by mila-sevilla** [comment]
Working on this in #269, since filtering for page title is the same logic as filtering for topics and sources
