### ISSUE TITLE
Search highlighting doesn't find whole title

### ISSUE THREAD

**Issue by mila-sevilla** [databyss-org/databyss#289]
When you search for the whole title of a source it doesn't find it/highlight it but strangely when you enter everything but the last letter, it finds it

![Screenshot 2020-06-30 at 17 02 19](https://user-images.githubusercontent.com/41082332/86142573-a1a53700-baf3-11ea-8b9e-e6f50cf55ab3.png)
![Screenshot 2020-06-30 at 17 02 24](https://user-images.githubusercontent.com/41082332/86142579-a36efa80-baf3-11ea-9d5f-7e37777fb289.png)
![Screenshot 2020-06-30 at 17 05 41](https://user-images.githubusercontent.com/41082332/86142841-f779df00-baf3-11ea-8fc7-ad13d67dc83d.png)

**Comment by pzhine** [comment]
This is actually due to #337 , so closing.
