### ISSUE TITLE
Loading a page with lots of MarkUp text takes too long

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#293]
I have been keeping a list of French words I am learning, and i have one italicized word per entry block. It seems that the reload takes awhile. I am wondering if this has to do with the fact that when you copy any of our MarkedUp text, there is always a carriage return placed after the end of the markedup text.

**Comment by pzhine** [comment]
Optimization task. First investigate where the delay is coming from (server, network, render, etc)
