### ISSUE TITLE
Topic index page shows source block

### ISSUE THREAD

**Issue by pzhine** [databyss-org/databyss#399]
**Observed behavior**
1. Create a page with a topic heading and an entry below it
2. Add a source from Google books below the entry
3. Go to the topic index page from the sidebar
4. The '@' symbol and your source search query appears in the index results

**Expected behavior**
The index page shouldn't show this proto-source block 

**Screenshots**
<img width="1280" alt="Screen Shot 2020-08-22 at 9 14 37 AM" src="https://user-images.githubusercontent.com/2692844/90956911-a8e42380-e458-11ea-99f8-77e61fc7a1ce.png">

**Comment by msenejoa** [comment]
fixed in #404
