### ISSUE TITLE
Tooltip Error has Returned

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#407]
When you highlight right to left and then click a markup (loc, bold, italics), the tooltip moves to the other position.

We fixed this on master, but I believe that Paul's highlight/scroll fix regressed back to this error.

**Comment by pzhine** [comment]
- [ ] Also, let's only show that menu on mouseup, like Notion, Medium, Slack. Showing it during drag just makes it harder to see what you're selecting
