### ISSUE TITLE
Mobile App Breaks in Certain Modes

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#553]
On Safari, when I click All Authors, I get a blank screen.

![Screen Shot 2020-10-05 at 9 13 39 AM](https://user-images.githubusercontent.com/57733385/95084166-8007ad00-06eb-11eb-8934-891a7d8c80c2.png)

On Chrome, I am not able to view any of my data. I just get a pinwheel.

**Comment by jansensan** [comment]
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1410355/95085220-e5a86900-06ec-11eb-84a1-ec1d9dabc383.png">

It seems likely that in `https://github.com/databyss-org/databyss/blob/master/packages/databyss-notes-mobile/modules/Sources/SourcesIndex.js#L31`, there could be a better error handling to ensure that no error is thrown when property is missing.

Also, a `firstName` or `lastName` prop should never be missing, but rather be set as an empty string (which would make this safer I believe)
